import Header from "@/components/Header/Header";
import "./globals.css";
import Footer from "@/components/Footer/Footer";

export const metadata = {
	title: "IT-TEST",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='ru'>
			<body>
				<Header />
				<>{children}</>
				<Footer />
			</body>
		</html>
	);
}
